#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 时代透镜

# Short bio or description (displayed in the header)
description: 用时间线挖掘新闻背后的政治

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://i.imgur.com/mQlrd16.png # color (https://i.imgur.com/36JRUNs.png) white (https://i.imgur.com/mqPKizg.png)


# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 留言
    url: https://chinatimeline.github.io/submit
  - name: 参与
    url: /how_to_contribute
  - name: 数据
    url: https://github.com/chinatimeline/data

# Pagination
paginate: 25

# Includes an icon in the footer for each username you enter
footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email: chinatimeline@protonmail.com
  facebook:
  flickr:
  github: chinatimeline/chinatimeline.github.io
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  twitter: # jekyllrb
  youtube: # channel/<your_long_string> or user/<user-name>
  hackmd: chinatimeline

# Text under the icons in footer
footer-text: >
  Powered by Jekyll <a href="https://github.com/AWEEKJ/kiko-now" target="_blank">Kiko Now</a> | <a href="https://plot.ly/" target="_blank">Plotly</a> | <a href="https://staticman.net/" target="_blank">Staticman</a> | <a href="https://www.chartjs.org/" target="_blank">Chartjs</a>
  <br><font color="blue">本站功能组件的选取一律以是否被<a href="https://github.com/gorhill/uBlock" target="_blank">uBlockOrigin</a>（默认设置）阻拦为准<font>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: # chinatimeline.disqus.com

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://chinatimeline.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-algolia

# Exclude these files from your production _site
exclude:
  - vendor
  - LICENSE
  - README.md
  - CNAME

algolia:
  application_id: AQ2NWA6FRT
  index_name:     Timeline # You can replace that with whatever name you want
  search_only_api_key: 533d855435d988fee73b330d3df4e41c
  files_to_exclude: [ideology_backup2.md, ideology_backup3.md, ideology_backup4.md, religion_backup2.md, religion_backup3.md, religion_backup4.md]

staticman:
  api: "https://staticman3.herokuapp.com/v3/entry/github/chinatimeline/chinatimeline.github.io/master/comments"
  path: "_data/comments"
